### ISSUE TITLE
考慮加入由 TCTP 提供的台灣本地化繁體中文版本

### ISSUE THREAD

**Issue by everland-3769** [StarCitizenToolBox/LocalizationData#14]
**星際公民繁體中文台灣本地化修正翻譯計畫(TCTP)** 提供了一個基於星際公民漢化組簡體中文翻譯版本所翻譯的品質穩定的台灣本地化繁體中文版本，並且持續穩定的進行更新。期望能夠將此版本加入至SC工具箱的社群翻譯列表中，提供繁體中文玩家們一個品質穩定的選擇。

---

> 星際公民繁體中文台灣本地化修正翻譯計畫 (TCTP)：
[Github](https://github.com/Orbit-Startech/StarCitizen-TCTP)・[Discord](https://discord.gg/4YKMayH2AD)・[巴哈姆特](https://forum.gamer.com.tw/C.php?bsn=23291&snA=789&tnum=2&subbsn=9)

**Comment by xkeyC** [comment]
直接 PR 至 TW 分支即可

**Comment by everland-3769** [comment]
> 直接 PR 至 TW 分支即可

PR了

**Comment by xkeyC** [comment]
> > 直接 PR 至 TW 分支即可
> 
> PR了

已同步至汉化盒子
